GET http://localhost:3333


###
POST http://localhost:3333/auth/register HTTP/1.1
content-type: application/json

{
    "name": "André",
    "email": "andrebass27@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3333/auth/authenticate HTTP/1.1
content-type: application/json

{
    "email": "andrebass27@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3333/projects/ HTTP/1.1